### PR TITLE
[#528] Add java sdk client configuration

### LINKED ISSUE #528: Investigate V4 signatures from S3 Java SDK
It seems that S3 Java SDK does not calculate signatures the way neofs-s3-gw expects. We had similar signature issues with other software (maybe it used Java SDK?)

If there is an option to configure Java client to be compatible with neofs-s3-gw, then describe it in README or docs.

If there is no way to configure Java client, then consider changes in neofs-s3-gw code to be compatible with both awscli and Java client.

### PR DESCRIPTION
**Pull request by KirillovDenis**
close #528 
Signed-off-by: Denis Kirillov <denis@nspcc.ru>

### CODE REVIEW

**Comment by alexvanin** [comment]
Should we mention GitHub discussion why some fields should be omitted? Are there any related discussion in S3 SDK Go repository?

**Comment by alexvanin** [comment]
> The problem is using different agents with pre-signed URLs

So it affects #529. In this PR I propose to check if it is possible to copy signature verification code in our repository and modify it so we will have functions to verify preisgned URLs and regular URLs. Check if `awscli` will be compatible. https://github.com/nspcc-dev/neofs-s3-gw/issues/528#issuecomment-1156037423

**Comment by KirillovDenis** [comment]
I think it should be rebased on #531

**Comment by alexvanin** [comment]
With `api/signer/v4` package is it possible to connect from default Java SDK Client to S3 Gateway?

**Comment by KirillovDenis** [comment]
> With `api/signer/v4` package is it possible to connect from default Java SDK Client to S3 Gateway?

Yes. It's a main goal to adopt `signer/v4`

**Review by alexvanin — APPROVED** [review]

**Pull request merged**
