### PR TITLE
Define default location constraint

### PR DESCRIPTION
**Pull request by alexvanin**
Fixes `test_bucket_get_location` from s3-tests.

Closes #468

### CODE REVIEW

**Comment by alexvanin** [comment]
Checking if it affects other tests.

**Comment by KirillovDenis** [comment]
Let's forbid this value (`default`) to be defined by user (https://github.com/nspcc-dev/neofs-s3-gw/blob/087d500c5f4c226059189642bc12e8fee0f3a8db/docs/authmate.md#containers-policy)

**Comment by alexvanin** [comment]
> Let's forbid this value (`default`) to be defined by user (https://github.com/nspcc-dev/neofs-s3-gw/blob/087d500c5f4c226059189642bc12e8fee0f3a8db/docs/authmate.md#containers-policy)

Done. Tell me if you think of better place to define default location constraint constant.

**Comment by KirillovDenis** [comment]
> Done. Tell me if you think of better place to define default location constraint constant.

What about this file https://github.com/nspcc-dev/neofs-s3-gw/blob/087d500c5f4c226059189642bc12e8fee0f3a8db/api/headers.go ?

**Review by KirillovDenis — APPROVED** [review]

**Review by KirillovDenis — APPROVED** [review]

**Pull request merged**
