### PR TITLE
Tree Service

### PR DESCRIPTION
**Pull request by alexvanin**
Rebased version of https://github.com/nspcc-dev/neofs-s3-gw/commit/f1d723348d9ee2225d0cc33349e41ca0cde2646c

Excluded commits:
- Disable CodeQL for tree-service branch  https://github.com/nspcc-dev/neofs-s3-gw/commit/2116a56d19c4943b06429781a37e7a2c70c9dd68

### CODE REVIEW

**Comment by alexvanin** [comment]
@realloc FYI, binary build requires internet connection (besides fetching dependencies) to fetch tree service client code from neofs-node repository.

**Comment by realloc** [comment]
I hope this temporary measure will be removed soon =)

**Comment by KirillovDenis** [comment]
@alexvanin could you fix empty line?
https://github.com/alexvanin/neofs-s3-gw/blob/e9723694d006a2d475e0231321f1934408b93f06/api/handler/cors.go#L8-L10

**Review by KirillovDenis — APPROVED** [review]

**Review by masterSplinter01 — APPROVED** [review]

**Comment by alexvanin** [comment]
Gonna merge after some tests

**Comment by alexvanin** [comment]
Basic workflows are fine. There are a few broken tests from s3-tests. Solve them in separate issues.

**Pull request merged**
